parameters:
  is_active:
    type: opcua
    node_id: "ns=2;s=SawMill/States/IsActive"
    data_type: boolean
    description: Machine active state
    monitor: true
    publish: true
    enabled: true
  is_working:
    type: opcua
    node_id: "ns=2;s=SawMill/States/IsWorking"
    data_type: boolean
    description: Machine working state
    monitor: true
    publish: true
    enabled: true
  is_stopped:
    type: opcua
    node_id: "ns=2;s=SawMill/States/IsStopped"
    data_type: boolean
    description: Machine stopped state
    monitor: true
    publish: true
    enabled: true
  cutting_speed:
    type: opcua
    node_id: "ns=2;s=SawMill/Parameters/CuttingSpeed"
    data_type: float
    description: Current cutting speed
    unit: m/s
    monitor: true
    publish: true
    enabled: true
  power_consumption:
    type: opcua
    node_id: "ns=2;s=SawMill/Parameters/PowerConsumption"
    data_type: float
    description: Current power consumption
    unit: kW
    monitor: true
    publish: true
    enabled: true
  pieces_count:
    type: opcua
    node_id: "ns=2;s=SawMill/Counters/PiecesCount"
    data_type: integer
    description: Number of pieces processed
    monitor: true
    publish: true
    enabled: true
  has_alarm:
    type: opcua
    node_id: "ns=2;s=SawMill/Alarms/HasAlarm"
    data_type: boolean
    description: Alarm state
    monitor: true
    publish: true
    enabled: true
  has_error:
    type: opcua
    node_id: "ns=2;s=SawMill/Alarms/HasError"
    data_type: boolean
    description: Error state
    monitor: true
    publish: true
    enabled: true